### ISSUE TITLE
Errors when running with --production flag

### ISSUE THREAD

**Issue by arggh** [FGM/filog#8] opened 2016-11-11 11:40 UTC
Reproduction here:

https://github.com/arggh/filog-prod-flag-issue

When running Meteor with `--production` flag, log entries triggered from the client side cause this to appear in the server log:

```
/sandbox/filog/prod-flag-issue$ meteor --production
Warning: The --production flag should only be used to simulate production bundling for testing purposes. Use meteor build to create a bundle for production deployment. See:
https://guide.meteor.com/deployment.html
[[[[[ /sandbox/filog/prod-flag-issue ]]]]]

=> Started proxy.                             
For compatibility, the PACKAGE_DIRS environment variable is deprecated and will be removed in a future Meteor release.
Developers should now use METEOR_PACKAGE_DIRS and Windows projects should now use a semi-colon (;) to separate paths.
=> Started MongoDB.                           
I20161111-13:26:26.964(2)? Serving logger on /logger
=> Started your app.

=> App running at: http://localhost:3000/
I20161111-13:26:32.495(2)? [SyntaxError: Unexpected end of input]
I20161111-13:26:32.495(2)? [SyntaxError: Unexpected token e]
I20161111-13:26:32.496(2)? [SyntaxError: Unexpected token l]
I20161111-13:26:32.496(2)? [SyntaxError: Unexpected token c]
I20161111-13:26:32.496(2)? [SyntaxError: Unexpected token r]
I20161111-13:26:32.496(2)? [SyntaxError: Unexpected token r]
I20161111-13:26:32.506(2)? [SyntaxError: Unexpected end of input]
I20161111-13:26:32.506(2)? [SyntaxError: Unexpected token }]
I20161111-13:26:32.506(2)? [SyntaxError: Unexpected token c]
I20161111-13:27:02.616(2)? [SyntaxError: Unexpected end of input]
I20161111-13:27:02.616(2)? [SyntaxError: Unexpected token e]
I20161111-13:27:02.617(2)? [SyntaxError: Unexpected token r]
I20161111-13:27:02.617(2)? [SyntaxError: Unexpected token /]
I20161111-13:27:02.618(2)? [SyntaxError: Unexpected token &]
I20161111-13:27:02.624(2)? [SyntaxError: Unexpected end of input]
I20161111-13:27:02.624(2)? [SyntaxError: Unexpected token }]
I20161111-13:27:02.624(2)? [SyntaxError: Unexpected token c]
```

The first log entry, triggered manually with `logger.warn`, does appear in the MongoDB collection, but the second one, triggered by calling an undefined function, does not.

Without the `--production` flag it works as expected. I have not yet tried it in a "real" production environment. Logging from the server side seems to work with or without the flag.

**Comment by FGM** [comment] 2016-11-11 13:09
Confirmed: the path received by the HTTP listener is not correct with that option.

**Comment by FGM** [comment] 2016-11-11 14:18
More detail: the errors happen while parsing the stack built by tracekit. The error disappears if the entire Error is not passed in reportSubscriber(), but the stack is stripped from it, like:

```
delete(e.stack);
this.log(LogLevel.ERROR, e.message, e);
```

Does this match your observations ?

**Comment by FGM** [comment] 2016-11-14 09:51
Found it: the error is in `ServerLogger.handleClientRequest()` which incorrectly assumes it will be only called a single time with the full message instead of handling streaming as it should. In turn, this is triggered because the stack in production mode currently contains the full source code whereis in development mode it only contains normal stack information, making it too big to be posted in a single buffer, which might need another, separate, fix.

**Comment by FGM** [comment] 2016-11-14 10:22
Addressing this issue in PR #9, so closing issue: followups in the PR.

**Closed by FGM** 2016-11-14 10:22 UTC
Labels: bug
